BmsApp/urls.py
from django.conf.urls import patterns, url, include
import views


urlpatterns = patterns('',

                       url(r'^index/', views.index, name='index'),
                       url(r'^$', views.index, name='index'),

                       url(r'^unit/(?P<unit_id>\d+)/$', views.detail_unit, name='detail_unit'),
                       url(r'^room/(?P<room_id>\d+)/$', views.detail_room, name='detail_room'),
                       url(r'^load/(?P<load_id>\d+)/$', views.detail_load, name='detail_load'),

                       #mobile urls
                       url(r'^index_m/', views.index, {'mobile_view' : True}, name='index_m'), #not very useful, since no room to select
                       url(r'^unit_m/(?P<unit_id>\d+)/$', views.detail_unit, {'mobile_view' : True}, name='detail_unit_m'),
                       url(r'^room_m/(?P<room_id>\d+)/$', views.detail_room, {'mobile_view' : True}, name='detail_room_m'),
                       url(r'^load_m/(?P<load_id>\d+)/$', views.detail_load, {'mobile_view' : True}, name='detail_load_m'),


)

SmartBuilding/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from BmsAPI.urlsAPI import urlsecpatterns
from SmartBuilding import settings
from SmartBuilding.settings import URL_SECRET_KEY
import password_reset.urls


admin.autodiscover()


urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', 'SmartBuilding.views.home', name='home'),
                       url(r'^home/', 'SmartBuilding.views.home', name='home'),
                       url(r'^BuildingWebApp/', include('BmsApp.urls', namespace="BmsApp")),
                       url(r'^contact/', 'SmartBuilding.views.contact', name='contact'),
                       url('', include('django.contrib.auth.urls')),
                       url(r'^password_reset/', include('password_reset.urls')),
                       url(r'^account/', 'SmartBuilding.views.authview', name='auth_account'),
                       url(r'^logout/', 'django.contrib.auth.views.logout', name="auth_logout"),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^logs/', 'SmartBuilding.views.logs' , name="django_log"),
                       url(r'^geolocation/', 'SmartBuilding.views.location' , name="current_location"),
                       url(r'^android/', 'SmartBuilding.views.android' , name="android"),
                       url(r'^joulesense/', 'SmartBuilding.views.joulesense' , name="joulesense"),
                       url(r'^vmiddleware/', 'SmartBuilding.views.vmiddleware' , name="vmiddleware"),
                       url(r'^easydashboard/', 'SmartBuilding.views.easydashboard' , name="easydashboard"),

                       #mobile urls
                       url(r'^home_m/', 'SmartBuilding.views.home', {'mobile_view' : True}, name='home_m'),
                       url(r'^contact_m/', 'SmartBuilding.views.contact', {'mobile_view' : True}, name='contact_m'),
                       url(r'^account_m/', 'SmartBuilding.views.authview', {'mobile_view' : True}, name='auth_account_m'),
                       url(r'^geolocation_m/', 'SmartBuilding.views.location', {'mobile_view' : True} , name="current_location_m"),
                       url(r'^android_m/', 'SmartBuilding.views.android', {'mobile_view' : True} , name="android_m"),
                       url(r'^joulesense_m/', 'SmartBuilding.views.joulesense', {'mobile_view' : True} , name="joulesense_m"),
                       url(r'^API/', include('BmsAPI.urlsAPI', namespace='BmsAPI')),
                       url(r'^APIsec/'+URL_SECRET_KEY+'/', include(urlsecpatterns, namespace='APIsec')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media\/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
)

SmartBuilding/views.py
from django.shortcuts import render
from django.contrib.auth.views import login
from django.views.decorators.http import require_http_methods, require_GET
from django.http import HttpResponse
from SmartBuilding import settings
from BmsApp.models import *
from mycontext import version_str
from conf_rtserver import *
from conf_general import PUB_MSG_TYPE

mobile_context = {"skip_navbar" : True, "general_mobile_view": True}
basic_context = {"static_serve_all_js_css": True}
central_loc = {"center_latitude" : 46.519468, "center_longitude" : 6.565315}

@require_GET
def home(request, mobile_view = False):
    context = {"centering_zoom" : mobile_view, "view_title":"openBMS "+version_str}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'home.html', render_context)


@require_GET
def contact(request, mobile_view = False):
    context = {"view_title": "openBMS Contact"}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'contact.html', render_context)


@require_http_methods(["GET","POST"])
def authview(request, mobile_view = False):
    context = {"view_title": "openBMS Account"}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return login(request, 'accounts.html', extra_context=render_context)


@require_GET
def location(request, mobile_view = False):
    if request.user.is_authenticated(): #try to get the location of interest of the user
        try:
            user_prof = UserProfile.objects.get(int_user=request.user.pk)
            unit_interest = user_prof.unit
            context = {"center_latitude" : unit_interest.latitude, "center_longitude" : unit_interest.longitude}
        except UserProfile.DoesNotExist:
            context = central_loc
    else:
        context = central_loc
    context["view_title"] = 'openBMS Location'
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'location.html', render_context)


@require_GET
def logs(request):
    if not request.user.is_staff:
        return HttpResponse('Unauthorized', status=401)
    logtext = []
    for line in open(settings.LOG_FILE).readlines()[:-500:-1]:
        logtext.append(line)
    return HttpResponse(logtext, status=200, content_type="text/plain")


@require_GET
def android(request, mobile_view = False):
    context = {"view_title": "openBMS Android"}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'android.html', render_context)

@require_GET
def joulesense(request, mobile_view = False):
    context = {"view_title": "openBMS JouleSence"}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'joulesense.html', render_context)



@require_GET
def vmiddleware(request, mobile_view = False):
    context = {"view_title": "openBMS vMiddleware"}
    websocket_context = {'rt_server_ip': RT_SERVER_IP, 'rt_server_port': RT_SERVER_PORT, 'rt_room_list': [],
                         'frontend_websock_id': PUB_ID_FRONTEND, 'extra_pub_id_list' : [PUB_ID_VMID_PING],
                         'websocket_msg_class': PUB_MSG_TYPE}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(websocket_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'vmiddleware.html', render_context)

@require_GET
def easydashboard(request, mobile_view = False):
    context = {"view_title": "openBMS Easy Dashboard"}
    render_context = {}
    render_context.update(basic_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'easydashboard.html', render_context)

SmartBuilding/templates/accounts.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 80%; margin-left: 30px; text-align: left; margin-top: 30px;">
        {% if user.is_authenticated %}
            <h4 style="margin-bottom: 20px;"> Your are logged in as: <b>{{ user.username }}</b></h4>
            {% if user.is_staff %}<a href="{% url 'admin:index' %}"><i class="fa fa-gear fa-fw"></i>Admin</a>{% endif %}
            <a href="{% url "password_reset_recover" %}"><i class="fa  fa-refresh fa-fw"></i>Change Password</a>
            <form role="form" method="POST" action="{% url 'django.contrib.auth.views.logout' %}">
                {% csrf_token %}
                <button style="margin-top: 10px" type="submit" class="btn btn-primary">Logout</button>
                {% if not skip_navbar %}
                    <input type="hidden" name="next" value="{% url 'auth_account' %}"/>
                {% else %}
                    <input type="hidden" name="next" value="{% url 'auth_account_m' %}"/>
                {% endif %}
            </form>
        {% else %}
            {% if not skip_navbar %}
                <form class="form-horizontal" role="form" method="POST" action="{% url 'auth_account' %}">
            {% else %}
                <form class="form-horizontal" role="form" method="POST" action="{% url 'auth_account_m' %}">
            {% endif %}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h4 style="margin-bottom: 20px;"> Login to Building Web App: </h4>
            </div>
        </div>
        {% csrf_token %}
        <div class="row" style="">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="form-group">
                    <label style="text-align:left" class="col-xs-5 col-sm-3 col-lg-3 col-md-3 control-label" for="id_username">Username:</label>
                    <div class="col-xs-5 col-sm-3 col-lg-3 col-md-3">
                        <input id="id_username" class="form-control" maxlength="254" name="username" type="text">
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="form-group">
                    <label style="text-align:left" class="col-xs-5 col-sm-3 col-lg-3 col-md-3 control-label" for="id_password">Password:</label>
                    <div class="col-xs-5 col-sm-3 col-lg-3 col-md-3">
                        <input id="id_password" class="form-control col-lg-3" name="password" type="password" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div  style="float: left;" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <div class="row" style="padding-left: 20px;">
            {% if form.errors %}
                <p style="margin-top: 20px; color: red">Your username and password didn't match. Please try again.</p>
            {% endif %}
            {% if not skip_navbar %}
                <input type="hidden" name="next" value="{% url 'auth_account' %}"/>
            {% else %}
                <input type="hidden" name="next" value="{% url 'auth_account_m' %}"/>
            {% endif %}
        </div>
        </form>
            {% block script_base %}
                {% if form.errors %}
                    <script>$('#id_password').parent().addClass('has-error')</script>
                    <script>$('#id_username').parent().addClass('has-error')</script>
                {% endif %}
            {% endblock %}
        {% endif %}

    </div>

{% endblock %}

SmartBuilding/templates/android.html
{% extends "base.html" %}
{% block content %}
    <div style="width: 70%; margin-left: 30px; text-align: left; margin-top: 30px; margin-bottom: 50px">
        <h3> Click on the logo to download the setup file </h3>
        <a href="{{ STATIC_URL }}app/openbmsclient.apk">
            <img style="width: 30%; float: left; margin-top: 30px;"
                 src="{{ STATIC_URL }}img/android_logo.png" alt="Android logo">
        </a>
    </div>
{% endblock %}

SmartBuilding/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="" name="description">
    <meta content="" name="author">
    <link rel="icon" href="{{ STATIC_URL }}img/favicon.png" type="image/png">

    <!-- Title and version -->
    <title>{{ view_title }}</title>
    {% if static_serve_all_js_css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-3.3.6.min.css" type="text/css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome-4.5.0.min.css" type="text/css">
        {% if not skip_main_js_files %}
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-3.3.6.min.js"></script>
        {% endif %}
    {% else %}
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" type="text/css">
        {% if not skip_main_js_files %}
        <script type="text/javascript" src="//code.jquery.com/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
        {% endif %}
    {% endif %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/mystyle.css" type="text/css">



    <!-- Add view specific header -->
    {% block additional_header %}{% endblock %}
</head>

{% if not skip_navbar %}
<body style="padding-top: 50px;">
{% else %}
<body>
{% endif %}
{% load customtags %}
{% gapless %}
    <div class="main-wrapper">
        {% if not skip_navbar %}
        {% include "navbar.html" %}
        {% endif %}
        <div class="content">
            <!-- The main content -->
            {% block content %}{% endblock %}
        </div>
    </div>

    <!-- The main script -->
    {% block script_base %}{% endblock %}
{% endgapless %}
</body>

</html>

SmartBuilding/templates/contact.html
{% extends "base.html" %}
{% block content %}
    <div style="width: 80%; margin-left: 30px; text-align: left; margin-top: 30px;">
        <div style="margin-bottom: 50px">
            <h3> Project developed and maintained for elab by: </h3>
            <h4>
            <i>George Lilis: georgios.lilis at epfl.ch</i>
            </h4>
        </div>

        <h4> Past contributors: </h4>
        <p style="margin-left: 2px">
            <i> Adrien Hoffet 2015</i>
        <br><i> Pierre Guillain 2014-2015</i>
        <br><i> Gilles Vetsch 2014-2015</i>
        <br><i> Thomas Guibentif 2014</i>
        </p>

    </div>

{% endblock %}

SmartBuilding/templates/easydashboard.html
{% extends "base.html" %}

{% block additional_header %}
{% comment %}
any additional headers you need go here
{% endcomment %}
{% endblock %}

{% block content %}
    <div class="col-xs-12 col-lg-7 col-md-7">
        <div class="row">
            <h3>Your dashboard html code goes here</h3>
        </div>
    </div>
{% endblock %}

{% block script_base %}
    <script>

    </script>

{% endblock %}

SmartBuilding/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div id="home_presentation" class="jumbotron text-center" style="background-color:white;">
    {% if not centering_zoom %}
        <h1>Welcome to <br> openBMS <i>{{ VERSION_APP }}</i></h1>
        <div style="width: 40%; margin: auto;"> {# we need margin auto for middle allignment #}
            <img style="width: 100%; display: block; margin: 30px auto;"
                 src="{{ STATIC_URL }}img/app_logo.png" alt="App logo">
        </div>
    {% else %}
        <h1>Welcome to <br> openBMS <i>{{ VERSION_APP }}</i></h1>
        <div style="align-self:center; margin: auto;"> {# we need margin auto for middle allignment #}
            <img style="width: 70%; display: block; margin: 30px auto;"
                 src="{{ STATIC_URL }}img/app_logo_m.png" alt="App logo">
        </div>
    {% endif %}
    </div>

{% endblock %}

SmartBuilding/templates/joulesense.html
{% extends "base.html" %}

{% block additional_header %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/circular-slider.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/flipclock.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/joulesense.css">

    <script src="{{ STATIC_URL }}js/circular-slider.min.js"></script>
    <script src="{{ STATIC_URL }}js/flipclock.min.js"></script>
{% endblock %}

{% block content %}
    <div class="col-xs-12 col-lg-7 col-md-7">
        <div class="row">
            <div id="slider"></div>
            <h3>Time to reach the temperature</h3>
            <div id="clock"></div>
        </div>
    </div>
{% endblock %}

{% block script_base %}
    <script>
        var current_temp=0;
        var set_temp=0;

        jQuery(function ($) {
                    get_single_sensor_ref_last_val() }
        );

        function get_single_sensor_ref_last_val() {
            $.ajax({
                type: 'GET',
                url: '{% url 'BmsAPI:lastRoomQuantity' 'TEM' '1' %}',
                dataType: "json",
                success: function (data) {
                    current_temp = data['TEM'][1];
                    set_temp = parseInt(current_temp); //slider takes only int
                    init_clock_slider()
                },
                timeout: 1000
            });
        }

        function init_clock_slider(){
            var clock = $('#clock').FlipClock({
                countdown: true,
                clockFace: 'MinuteCounter',
                autoStart: false
            });

            var default_font_size;
            var circularSlider = $('#slider').CircularSlider({
                min : 10,
                max: 32,
                value : set_temp,
                shape : 'Half Circle',
                animateDuration: 1000,
                labelSuffix: "&deg;",
                handleDist: 95,
                radius: 100,
                innerCircleRatio: '0.65',
                slide : function(ui, value) {
                    var center_cycle = $('.jcs-value');
                    if(value<current_temp){
                        center_cycle.css({'background-color': '#c4def0', 'border-color': '#FFFFFF', 'color': '#FFFFFF'});
                    }
                    else if(value<25){
                        center_cycle.css({'background-color': '#5FCD3A', 'border-color': '#EFFAEB', 'color': '#FFFFFF'});
                    }
                    else if(value<30){
                        center_cycle.css({'background-color': '#CD5134', 'border-color': '#CDB094', 'color': '#FFFFFF'});
                    }
                    else{
                        center_cycle.css({'background-color': '#B00500', 'border-color': '#B0A0A9', 'color': '#FFFFFF'});
                    }

                    set_temp = center_cycle.html(); //Store it
                    center_cycle.css({'font-size': default_font_size});
                },
                onSlideEnd : function(ui, value) {
                    start_timer();

                }
            });

            function start_timer(){
                var value = parseInt(set_temp.substring(0, set_temp.length-1));
                if (value>current_temp){
                    clock.stop();
                    clock.setTime(value*10*0.8*(value-current_temp));
                    clock.start();
                }
                else{
                    clock.stop();
                    clock.setTime(0);
                }
            }

            {#        $(document).ready(function(){#}
            {#            $('#slider').click(function(){#}
            {#                start_timer();#}
            {#            });#}
            {#        });#}

            var toggle_state = true; //To know the current state of display(set temp vs current)
            default_font_size = $('.jcs-value').css('font-size');
            function flash_current_t(){
                if(toggle_state){
                    $('.jcs-value').html('Current '+current_temp+"&deg;");
                    $('.jcs-value').css({'font-size': '110%'});
                    toggle_state = false
                }
                else{
                    $('.jcs-value').html(set_temp);
                    $('.jcs-value').css({'font-size': default_font_size});
                    toggle_state = true
                }

            }

            setInterval(function () {
                flash_current_t()}, 3000);
        }

    </script>

{% endblock %}

SmartBuilding/templates/location.html
{% extends "base.html" %}

{% block additional_header %}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
{% endblock %}

{% block content %}
    <article style="margin-left: 20px; margin-right: 20px">
        <p><span class="label label-info" id="status">Finding your location...</span>
            <span class="label label-default" id="coordinates"></span>
        </p>
        <p>
            <span class="label label-default" id="distance"></span>
        </p>
    </article>
    <script>
        function success(position) {
            var s = document.querySelector('#status');
            var cor = document.querySelector('#coordinates');

            var origin = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            var destination = new google.maps.LatLng({{center_latitude}},{{center_longitude}});

            var service = new google.maps.DistanceMatrixService();
            service.getDistanceMatrix(
                    {
                        origins: [origin],
                        destinations: [destination],
                        travelMode: google.maps.TravelMode.WALKING,
                        unitSystem: google.maps.UnitSystem.METRIC,
                    }, callback);



            if (s.className == 'success') {
                // not sure why we're hitting this twice in FF, I think it's to do with a cached result coming back
                return;
            }

            s.innerHTML = "I found you with accuracy of "+Math.round(position.coords.accuracy * 100) / 100+" meters";
            s.className = "label label-success";
            cor.innerHTML = "Latitude: "+position.coords.latitude+" Longitude: "+position.coords.longitude;

            var mapcanvas = document.createElement('div');
            mapcanvas.id = 'mapcanvas';
            mapcanvas.style.height = '300px';
            //mapcanvas.style.width = '560px';

            document.querySelector('article').appendChild(mapcanvas);

            var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

            var myOptions = {
                zoom: 15,
                center: latlng,
                mapTypeControl: false,
                navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            var map = new google.maps.Map(document.getElementById("mapcanvas"), myOptions);

            var marker = new google.maps.Marker({
                position: destination,
                map: map,
                title: 'Location of unit of interest',
                icon: '/static/img/google_markers/brown_markerA.png'
            });

            var marker = new google.maps.Marker({
                position: latlng,
                map: map,
                title:"You are here! (at least within a "+Math.round(position.coords.accuracy * 100) / 100+" meter radius)",
                icon: '/static/img/google_markers/red_markerA.png'
            });
        }

        function error(msg) {
            var s = document.querySelector('#status');
            s.innerHTML = typeof msg == 'string' ? msg : "failed";
            s.className = 'fail';
        }

        function callback(response, status) {
            var s = document.querySelector('#distance');
            if (status == google.maps.DistanceMatrixStatus.OK) {

                var results = response.rows[0].elements;
                var element = results[0];
                var distance = element.distance.text;
                var duration = element.duration.text;
                s.innerHTML = "Distance to central unit "+distance+" and expected walking time "+duration
            }
            else {
                alert('Geocode was not successful for the following reason: '
                        + status);
            }


        }

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, error);
        } else {
            error('not supported');
        }

    </script>

{% endblock %}

SmartBuilding/templates/navbar.html
<div class="navbar navbar-inverse navbar-static-top navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">openBMS <span class="navbar-header-ver">{{ VERSION_APP }}</span></a>
        </div>
        <div class="navbar-collapse collapse ">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-leaf fa-fw fa-lg"></i>WebApps<i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-apps">
                        <li><a href="{% url 'BmsApp:index' %}">
                            <i class="fa fa-area-chart fa-fw"></i>Main Dashboard</a></li>
                        <li><a href="{% url 'easydashboard' %}">
                            <i class="fa fa-pie-chart fa-fw"></i>Easy Dashboard</a></li>
                        <li><a href="{% url 'vmiddleware' %}">
                            <i class="fa fa-heartbeat fa-fw"></i>Virtualization</a></li>
                        <li><a href="http://{{ REALTIMESERVER }}/debug">
                            <i class="fa fa-cogs fa-fw"></i>RealTime Server</a></li>
                        <li><a href="{% url 'joulesense' %}">
                            <i class="fa fa-clock-o fa-fw"></i>JouleSense</a></li>
                        <li><a href="http://thinkee.epfl.ch">
                            <i class="fa fa-comments fa-fw"></i>ThinkEE</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-mobile fa-fw fa-lg"></i>Mobile Apps<i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-apps">
                        <li><a href="{% url 'BmsApp:index_m' %}">
                            <i class="fa fa-area-chart fa-fw"></i>Mobile Dashboard</a></li>
                        <li><a href="{% url 'android' %}">
                            <i class="fa fa-android fa-fw"></i>Android App</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-code fa-fw"></i>API<i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-apps">
                        <li><a href="{% url 'BmsAPI:docsAPI' %}">
                            <i class="fa fa-book fa-fw"></i>API documentatiuon</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>Help<i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li><a href="{% url 'contact' %}">
                            <i class="fa fa-ambulance fa-fw"></i>Contact</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>User<i class="fa fa-caret-down"></i></a>
                    <ul class="dropdown-menu dropdown-user">
                        {% if user.is_authenticated %}
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin:index' %}">
                                    <i class="fa fa-gear fa-fw"></i>Admin</a></li>
                                <li><a href="{% url 'django_log' %}">
                                    <i class="fa fa-file-text-o fa-fw"></i>Log File</a></li>
                            {% endif %}
                            <li><a href="{% url 'auth_account' %}">
                                <i class="fa fa-user fa-fw"></i>Profile of {{ user.username }}</a></li>
                            <li><a href="{% url 'current_location' %}">
                                <i class="fa fa-compass fa-fw"></i>Location</a></li>
                            <li><a href="{% url 'auth_logout' %}?next={% url 'auth_account' %}">
                                <i class="fa fa-sign-out fa-fw"></i>Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'auth_account' %}">
                                <i class="fa fa-sign-in fa-fw"></i>Login</a></li>
                            <li><a href="{% url "password_reset_recover" %}">
                                <i class="fa  fa-refresh fa-fw"></i>Reset Password</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>