BmsApp/urls.py
from django.conf.urls import patterns, url, include
import views


urlpatterns = patterns('',

                       url(r'^index/', views.index, name='index'),
                       url(r'^$', views.index, name='index'),

                       url(r'^unit/(?P<unit_id>\d+)/$', views.detail_unit, name='detail_unit'),
                       url(r'^room/(?P<room_id>\d+)/$', views.detail_room, name='detail_room'),
                       url(r'^load/(?P<load_id>\d+)/$', views.detail_load, name='detail_load'),

                       #mobile urls
                       url(r'^index_m/', views.index, {'mobile_view' : True}, name='index_m'), #not very useful, since no room to select
                       url(r'^unit_m/(?P<unit_id>\d+)/$', views.detail_unit, {'mobile_view' : True}, name='detail_unit_m'),
                       url(r'^room_m/(?P<room_id>\d+)/$', views.detail_room, {'mobile_view' : True}, name='detail_room_m'),
                       url(r'^load_m/(?P<load_id>\d+)/$', views.detail_load, {'mobile_view' : True}, name='detail_load_m'),


)

SmartBuilding/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from BmsAPI.urlsAPI import urlsecpatterns
from SmartBuilding import settings
from SmartBuilding.settings import URL_SECRET_KEY
import password_reset.urls


admin.autodiscover()


urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', 'SmartBuilding.views.home', name='home'),
                       url(r'^home/', 'SmartBuilding.views.home', name='home'),
                       url(r'^BuildingWebApp/', include('BmsApp.urls', namespace="BmsApp")),
                       url(r'^contact/', 'SmartBuilding.views.contact', name='contact'),
                       url('', include('django.contrib.auth.urls')),
                       url(r'^password_reset/', include('password_reset.urls')),
                       url(r'^account/', 'SmartBuilding.views.authview', name='auth_account'),
                       url(r'^logout/', 'django.contrib.auth.views.logout', name="auth_logout"),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^logs/', 'SmartBuilding.views.logs' , name="django_log"),
                       url(r'^geolocation/', 'SmartBuilding.views.location' , name="current_location"),
                       url(r'^android/', 'SmartBuilding.views.android' , name="android"),
                       url(r'^joulesense/', 'SmartBuilding.views.joulesense' , name="joulesense"),
                       url(r'^vmiddleware/', 'SmartBuilding.views.vmiddleware' , name="vmiddleware"),
                       url(r'^easydashboard/', 'SmartBuilding.views.easydashboard' , name="easydashboard"),

                       #mobile urls
                       url(r'^home_m/', 'SmartBuilding.views.home', {'mobile_view' : True}, name='home_m'),
                       url(r'^contact_m/', 'SmartBuilding.views.contact', {'mobile_view' : True}, name='contact_m'),
                       url(r'^account_m/', 'SmartBuilding.views.authview', {'mobile_view' : True}, name='auth_account_m'),
                       url(r'^geolocation_m/', 'SmartBuilding.views.location', {'mobile_view' : True} , name="current_location_m"),
                       url(r'^android_m/', 'SmartBuilding.views.android', {'mobile_view' : True} , name="android_m"),
                       url(r'^joulesense_m/', 'SmartBuilding.views.joulesense', {'mobile_view' : True} , name="joulesense_m"),
                       url(r'^API/', include('BmsAPI.urlsAPI', namespace='BmsAPI')),
                       url(r'^APIsec/'+URL_SECRET_KEY+'/', include(urlsecpatterns, namespace='APIsec')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media\/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
)

BmsApp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET
from BmsApp.models import *
from collections import OrderedDict
from conf_general import PUB_MSG_TYPE
from conf_rtserver import RT_SERVER_IP, RT_SERVER_PORT, PUB_ID_FRONTEND, PUB_ID_BMS_USER_REC, PUB_ID_BMS_USER_LOC
from conf_openbms import DJANGO_TIMEOUT_TIMESERIES, DJANGO_TIMEOUT_LASTVALUE, DJANGO_TIMEOUT_ACTION, DJANGO_TIMEOUT_STATUS, DJANGO_ENERGYRES, \
    DJANGO_UPDATE_INTERVAL, DJANGO_UPDATE_GRAPH_INTERVAL, DJANGO_MAX_POWERBAR, DJANGO_MAX_CO2GAUGE, DJANGO_MAX_COSTGAUGE, DJANGO_MAX_ENERGYGAUGE, DJANGO_MAX_SAMPLES

def create_contexts():
    """reads from DB and creates the essential context variables in memory. The views pick the context they need to include from
    the globals and update the context dictionaries."""
    global basic_context, timeout_context, extra_conf_context, websocket_context
    global type_list

    unit_list = Unit.objects.all()
    unit_ord_list = Unit.objects.order_by('name')
    device_list = Device.objects.all()
    type_list = DeviceType.objects.all()
    weatherlocation = Parameter.objects.get(name='weatherloc').value
    kwhprice = Parameter.objects.get(name='kwhprice').value
    co2perkhw = Parameter.objects.get(name='co2perkhw').value

    #The fundamental context for all views
    basic_context = {'unit_list': unit_list, 'unit_ord_list': unit_ord_list, 'type_list': type_list, 'device_list': device_list,
                 'weatherloc':weatherlocation, 'kwhprice': kwhprice, 'co2perkhw': co2perkhw, "static_serve_all_js_css": True}

    #The timeout context in the future we may take them from a DB
    timeout_timeseries = DJANGO_TIMEOUT_TIMESERIES
    timeout_lastvalue = DJANGO_TIMEOUT_LASTVALUE
    timeout_action = DJANGO_TIMEOUT_ACTION
    timeout_status = DJANGO_TIMEOUT_STATUS
    timeout_context = {'timeout_timeseries':timeout_timeseries, 'timeout_lastvalue': timeout_lastvalue,
                       'timeout_action': timeout_action, 'timeout_status': timeout_status}

    #Misc conf context
    energyres  = DJANGO_ENERGYRES # The resolution of the intergrator of energy
    updateinterval = DJANGO_UPDATE_INTERVAL #the update interval of the last points
    updategraphinterval = DJANGO_UPDATE_GRAPH_INTERVAL #the update interval of the graph, the overhead is to the client
    maxsamples = DJANGO_MAX_SAMPLES

    maxpowerbar = DJANGO_MAX_POWERBAR
    maxenergygauge = DJANGO_MAX_ENERGYGAUGE
    maxcostgauge = DJANGO_MAX_COSTGAUGE
    maxco2gauge = DJANGO_MAX_CO2GAUGE

    extra_conf_context = {'energyres': energyres, 'updateinterval': updateinterval, 'updategraphinterval': updategraphinterval,
                   'maxsamples':maxsamples, 'maxpowerbar': maxpowerbar, 'maxenergygauge': maxenergygauge,
                   'maxcostgauge': maxcostgauge, 'maxco2gauge': maxco2gauge,}

    websocket_context = {'rt_server_ip': RT_SERVER_IP, 'rt_server_port': RT_SERVER_PORT, 'rt_room_list': [],
                         'frontend_websock_id': PUB_ID_FRONTEND, 'extra_pub_id_list' : [PUB_ID_BMS_USER_REC]+[PUB_ID_BMS_USER_LOC],
                         'websocket_msg_class': PUB_MSG_TYPE}


create_contexts() #initial config

#The mobile view related context
#general_mobile_view takes priority and skips all unnecessary elements from webapp to show a mobile view
mobile_context = {"skip_navbar" : True, "general_mobile_view": True}


@require_GET
def index(request, mobile_view = False):
    if request.META['HTTP_USER_AGENT'] == 'android/app': mobile_view=True #Failsafe in case the app requests a regular url (non mobile)
    context = { "view_title": "openBMS WebApp | Index"}
    create_contexts()
    render_context = {}
    render_context.update(basic_context)
    render_context.update(websocket_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'index.html', render_context)


@require_GET
def detail_unit(request, unit_id, mobile_view = False):
    if request.META['HTTP_USER_AGENT'] == 'android/app': mobile_view=True #Failsafe in case the app requests a regular url (non mobile)
    unit = get_object_or_404(Unit, pk=unit_id)
    context = {'unit': unit, "view_title": "openBMS WebApp | Unit "+unit.name}
    create_contexts()
    render_context = {}
    render_context.update(basic_context)
    render_context.update(websocket_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'detail_unit.html', render_context)


@require_GET
def detail_room(request, room_id, mobile_view = False):
    global type_list
    if request.META['HTTP_USER_AGENT'] == 'android/app': mobile_view=True #Failsafe in case the app requests a regular url (non mobile)
    room = get_object_or_404(Room, pk=room_id)

    all_actuators = room.actuator_set.all()
    all_sensors = room.sensor_set.exclude(measure__in=Sensor.aux_measures)
    sensors = room.sensor_set.filter(measure__in=Sensor.room_measures) # Room sensors only
    bat_sensors = room.sensor_set.filter(measure__in=Sensor.batterylvl_measure) # battery sensors only

    load_sensors_list = room.sensor_set.filter(measure__in=Sensor.load_measures).exclude(load=None).values_list('measure', flat=True) # Load sensors only

    #All load objects of room by scanning the sensors
    load_list = room.load_set()

    load_per_devtype_list = {}
    for type in type_list:
        load_per_devtype_list[type.id] = room.load_set__type(type)

    ref_list_room = []
    for sensor in sensors:  # Room sensors only
        if sensor.ref not in ref_list_room:
            ref_list_room.append(sensor.ref)
    sensors_per_ref = {}
    sensors_with_bat = {}
    for reference in ref_list_room: # Room sensors only
        sensors_per_ref[reference] = sensors.filter(ref=reference)
        sensors_with_bat[reference] = bat_sensors.filter(ref=reference) #It would be only one per ref
    # List of settin
    # Take the from setting table now
    settings = room.roomsetting_set.all()
    setting_list = []
    for setting in settings:
        settingtype = [item[1] for item in Sensor.ROOM_CHOICES if item[0] == setting.set_quantity][0]
        setting_list.append((settingtype, setting.set_value, Sensor.room_choices_units[setting.set_quantity], setting))

    # Sorting according to human readable name
    setting_list = sorted(setting_list, key=lambda sett: sett[0])

    roomremark_list = room.roomremark_set.all()

    measure_units_all = dict(Sensor.room_choices_units.items() + Sensor.load_choices_units.items() + {'E':'Wh'}.items())
    powers_type = OrderedDict(Sensor.LOAD_CHOICES) # It is a dict that maps the internal with human readable choices
    for key in powers_type.keys():  #Remove the power type if no load sensor in room supports it.
        if not key in load_sensors_list:
            del powers_type[key]
    #This holds the keys of the interested room id to be transfered to rtserver
    rt_room_list = [int(room_id)]

    sensors_type = OrderedDict(Sensor.ROOM_CHOICES)
    context = {'room': room, 'isroomview' : True,
               'load_per_devtype_list': load_per_devtype_list, 'load_list':load_list ,
               'room_sensors_list': sensors, 'measure_units_all': measure_units_all,
               'load_measures_to_quantities': powers_type, 'room_measures_to_quantities': sensors_type,
               'actuators_list': all_actuators, 'ref_list_room': ref_list_room,
               'sensors_per_ref': sensors_per_ref, "sensors_with_bat":sensors_with_bat,
               'all_sensors': all_sensors, 'setting_list': setting_list, 'roomremark_list': roomremark_list, 'rt_room_list': rt_room_list,
               "view_title": "openBMS WebApp | Room " + room.name
    }
    create_contexts()
    render_context = {}
    render_context.update(basic_context)
    render_context.update(timeout_context)
    render_context.update(extra_conf_context)
    render_context.update(websocket_context)
    render_context.update(context)
    if mobile_view:
        render_context.update(mobile_context)
    return render(request, 'detail_room.html', render_context)


@require_GET
def detail_load(request, load_id, mobile_view = False):
    if request.META['HTTP_USER_AGENT'] == 'android/app': mobile_view=True #Failsafe in case the app requests a regular url (non mobile)
    load = get_object_or_404(Load, pk=load_id)

    sensors = load.sensor_set.exclude(measure__in=Sensor.aux_measures)
    actuators = load.actuator_set.all()
    ref_list = []
    load_sensors_list = []
    for sensor in sensors:
        if sensor.ref not in ref_list:
            ref_list.append(sensor.ref)  # All are load sensor of course
        if sensor.measure not in load_sensors_list:
            load_sensors_list.append(sensor.measure)
    sensors_per_ref = {}
    for reference in ref_list:
        sensors_per_ref[reference] = load.sensor_set.exclude(measure__in=Sensor.aux_measures).filter(ref=reference)

    powers_type = OrderedDict(Sensor.LOAD_CHOICES)
    for key in powers_type.keys():  #Remove the power type if no load sensor.
        if not key in load_sensors_list:
            del powers_type[key]
    measure_units_all = dict(Sensor.room_choices_units.items() + Sensor.load_choices_units.items())
    #This holds the keys of the interested room id to be transfered to rtserver
    if load.room():#in case load not in room
        load_room = load.room()
        rt_room_list = [int(load_room.id)]
    else:
        load_room = None
        rt_room_list = []
    context = {'load': load, 'room': load_room, 'isroomview' : False,
               'ref_list': ref_list, 'sensors_per_ref': sensors_per_ref, 'actuators_list': actuators,
               'load_sensors': sensors, 'all_sensors': sensors,
               'measure_units_all': measure_units_all, 'load_measures_to_quantities': powers_type,
               'rt_room_list': rt_room_list,

BmsApp/templates/detail_unit.html
{% extends "index_base.html" %}

{% block type %}
    <span style="float:left">Specifications of the unit: </span>
{% endblock %}
{% block name %}
    <span style="float:left;color:#333333;padding-left:5px">{{ unit.name }}</span>
{% endblock %}

{% block specifics %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <ul>
        <h3> Rooms: </h3>
        {% for room in unit.room_ord_set %}
            {% if not general_mobile_view %}
                {#  auto color the Outside...#}
                {% if room.name != 'Outside'%}
                    <a id="room_btn" class="btn btn-default" href="{% url 'BmsApp:detail_room' room.id %}"
                       role="button">{{ room.name }}</a>
                {% else %}
                    <a id="room_btn" class="btn btn-info" href="{% url 'BmsApp:detail_room' room.id %}"
                       role="button">{{ room.name }}</a>
                {% endif %}
            {% else %}
                {#  auto color the Outside...#}
                {% if room.name != 'Outside'%}
                    <a id="room_btn" class="btn btn-default" href="{% url 'BmsApp:detail_room_m' room.id %}"
                       role="button">{{ room.name }}</a>
                {% else %}
                    <a id="room_btn" class="btn btn-info" href="{% url 'BmsApp:detail_room_m' room.id %}"
                       role="button">{{ room.name }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}

    </ul>
{% endblock %}

BmsApp/templates/index.html
{% extends "index_base.html" %}

{% block type %}
    Room
{% endblock %}

{% block specifics %}
    <h4 style="padding: 10px 10px 10px 10px">
    {% if not general_mobile_view %}
        Please choose a room from units to see its status
    {% else %}
        {# Add at least a unit and room list for mobile navigation #}
        {# The mobile view doesnt have left sidebar. Move it in the specifics block #}
        {% include "unit_room_sidebar.html" %}
    {% endif %}
    </h4>
{% endblock %}

BmsApp/templates/load_rec_modal.html
<div class="modal fade load_rec_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span id="load_rec_modal_title"></span>  was pluged <i class="fa fa-plug"></i></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="container col-xs-12 col-lg-12 col-md-12">
                        <div class="row">
                            <div class="container col-xs-3">
                                <div id="device_pic"></div>
                            </div>
                            <div class="container col-xs-9">
                                <div class="row">
                                    <div class="container col-xs-5">
                                        <h5>Load name:</h5>
                                    </div>
                                    <div class="container col-xs-7">
                                        <h5 class="data" id="load_name"></h5>
                                    </div>
                                    <div class="container col-xs-5">
                                        <h5>Device type:</h5>
                                    </div>
                                    <div class="container col-xs-7">
                                        <h5 class="data" id="device_name"></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="container col-xs-12 col-lg-12 col-md-12 extra_info">
                        {#Place holder for more info#}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function load_rec_fill_data(load_data_payload){
        //Loads the data to modal
        //name surname profile_pic are
        var modal_body = $('.load_rec_modal .modal-body');
        var modal_header = $('.load_rec_modal .modal-header');
        var device_pic = '<img class="img-responsive" id="theImg" src="'+ load_data_payload['device_image'] +'" />';

        modal_header.find('#load_rec_modal_title').html(load_data_payload['load_name']);
        modal_body.find('#device_pic').html(device_pic);
        modal_body.find('#device_name').html(load_data_payload['device_name']);
        modal_body.find('#load_name').html(load_data_payload['load_name']);

        //reset the extra
        var extra_info = modal_body.find('.extra_info');
        extra_info.html('');
        if (load_data_payload['load_room_id']){
            extra_info.append('<div class="row">'+
                    '<div class="container col-xs-5">'+
                    '<h5>Current Location:</h5>'+
                    '</div>'+
                    '<div class="container col-xs-7">'+
                    '<h5 class="data" id="load_cur_loc"></h5>'+
                    '</div>'+
                    '</div>');
            {% if not general_mobile_view %}
                var room_url = "{% url 'BmsApp:detail_room' 99999 %}".replace(99999, load_data_payload['load_room_id']);
            {% else %}
                var room_url = "{% url 'BmsApp:detail_room_m' 99999 %}".replace(99999, load_data_payload['load_room_id']);
            {% endif %}
            var room_link = '<a href="' + room_url + '">' + load_data_payload['load_room_name'] + '</a>';
            modal_body.find('#load_cur_loc').html(room_link);
        }
        $('.load_rec_modal').on('shown.bs.modal', function () {
            $('.modal-body').css({'max-height': '100%'});
        });

    }
</script>

BmsApp/templates/new_load_modal.html
{% load customfilters %}
<div class="modal fade new_load_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">A new load has been detected. Please fill the following characteristics:</h4>
            </div>
            <div class="modal-body">
                <div class="container col-xs-12 col-lg-12 col-md-12">
                    <div class="row">
                        <div class="container col-xs-6">
                            <h4>Name of the actuator:</h4>
                        </div>
                        <div class="container col-xs-6">
                            <h4 data-actid='' id="Name_act"></h4>
                        </div>
                    </div>
                </div>
                <div class="container col-xs-12 col-lg-12 col-md-12">
                    <div class="row">
                        <div class="container col-xs-5">
                            <h4>UUID of the load:</h4>
                        </div>
                        <div class="container col-xs-7">
                            <h4 id="ld_uuid"></h4>
                        </div>
                    </div>
                </div>
                <div class="container col-xs-12 col-lg-12 col-md-12">
                    <h4><span class="hidden fa fa-remove" style="color:red"></span>Name of the load:</h4>
                    <div class="row">
                        <div class="col-xs-12 col-lg-12 col-md-12">
                            <input id="Name_load" type="text" class="form-control"/>
                        </div>
                    </div>
                </div>
                <div class="container col-xs-12 col-lg-12 col-md-12">
                    <h4>Type of the load:</h4>
                    <div class="row">
                        <div class="col-xs-12 col-lg-12 col-md-12">
                            <select  id="Type_load" class="form-control">
                                {% for type in type_list %}
                                    <option value='{{type.id}}'>{{type.name}}</option>
                                {% endfor%}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="container col-xs-12 col-lg-12 col-md-12">
                    <h4>Type of device:</h4>
                    <div class="row">
                        <div class="col-xs-12 col-lg-12 col-md-12">
                            <select  id="Type_device" class="form-control">
                                {% for type in type_list %}
                                    {% for device in device_list|by_type:type.id %}
                                        <option value='{{type.id}}' data-deviceid='{{device.id}}'>{{device.name}}</option>
                                    {% endfor%}
                                {% endfor%}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
                <button onclick="save_new_load()" type="button" class="btn btn-primary btn-accept">Save</button>
            </div>
        </div>
    </div>
</div>

BmsApp/templates/unit_room_sidebar.html
{% if unit_list %}
    {% for unit in unit_ord_list %}
        <div class="panel panel-default">
            <div class="panel-heading" id="collapse-button">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#unit_{{ unit.id }}">
                        <span class="fa fa-building"></span>
                        {{ unit.name }}
                    </a>
                </h4>
            </div>
            <div id="unit_{{ unit.id }}" class="panel-collapse collapse">
                <div class="panel-body">
                    {% for room in unit.room_ord_set %}
                        {% if not general_mobile_view %}
                            {#  auto color the Outside...#}
                            {% if room.name != 'Outside'%}
                                <a id="room_btn" class="btn btn-default" href="{% url 'BmsApp:detail_room' room.id %}"
                                   role="button">{{ room.name }}</a>
                                <br>
                            {% else %}
                                <a id="room_btn" class="btn btn-info" href="{% url 'BmsApp:detail_room' room.id %}"
                                   role="button">{{ room.name }}</a>
                                <br>
                            {% endif %}
                        {% else %}
                            {#  auto color the Outside...#}
                            {% if room.name != 'Outside'%}
                                <a id="room_btn" class="btn btn-default" href="{% url 'BmsApp:detail_room_m' room.id %}"
                                   role="button">{{ room.name }}</a>
                                <br>
                            {% else %}
                                <a id="room_btn" class="btn btn-info" href="{% url 'BmsApp:detail_room_m' room.id %}"
                                   role="button">{{ room.name }}</a>
                                <br>
                            {% endif %}
                        {% endif %}

                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <p>No units are available.</p>
{% endif %}

BmsApp/templates/user_rec_modal.html
<div class="modal fade user_rec_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Welcome <span id="user_rec_modal_title"></span>  <i class="fa fa-smile-o"></i></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="container col-xs-12 col-lg-12 col-md-12">
                        <div class="row">
                            <div class="container col-xs-2">
                                <div id="user_profile_pic"></div>
                            </div>
                            <div class="container col-xs-10">
                                <div class="row">
                                    <div class="container col-xs-5">
                                        <h5>First Name:</h5>
                                    </div>
                                    <div class="container col-xs-7">
                                        <h5 class="data" id="user_fname"></h5>
                                    </div>

                                    <div class="container col-xs-5">
                                        <h5>Last Name:</h5>
                                    </div>
                                    <div class="container col-xs-7">
                                        <h5 class="data" id="user_lname"></h5>
                                    </div>
                                    <div class="container col-xs-12 col-lg-12 col-md-12 extra_info">
                                        {#Place holder for more info#}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function user_rec_fill_data(user_data_payload){
        //Loads the data to modal
        //name surname profile_pic are
        var modal_body = $('.user_rec_modal .modal-body');
        var modal_header = $('.user_rec_modal .modal-header');
        var profile_pic = '<img class="img-responsive" id="theImg" src="'+ user_data_payload['profile_image'] +'" />';

        modal_header.find('#user_rec_modal_title').html(user_data_payload['name']);
        modal_body.find('#user_profile_pic').html(profile_pic);
        modal_body.find('#user_fname').html(user_data_payload['name']);
        modal_body.find('#user_lname').html(user_data_payload['surname']);

        //reset the extra
        var extra_info = modal_body.find('.extra_info');
        extra_info.html('');
        if (user_data_payload['ref_unit_id']){
            extra_info.append('<div class="row">'+
                    '<div class="container col-xs-5">'+
                    '<h5>Unit Interested:</h5>'+
                    '</div>'+
                    '<div class="container col-xs-7">'+
                    '<h5 class="data" id="user_int_unit"></h5>'+
                    '</div>'+
                    '</div>');
            {% if not general_mobile_view %}
                var unit_url = "{% url 'BmsApp:detail_unit' 99999 %}".replace(99999, user_data_payload['ref_unit_id']);
            {% else %}
                var unit_url = "{% url 'BmsApp:detail_unit_m' 99999 %}".replace(99999, user_data_payload['ref_unit_id']);
            {% endif %}
            var unit_link = '<a href="' + unit_url + '">' + user_data_payload['ref_unit_name'] + '</a>';
            modal_body.find('#user_int_unit').html(unit_link);

        }
        if (user_data_payload['cur_room_id']){
            extra_info.append('<div class="row">'+
                    '<div class="container col-xs-5">'+
                    '<h5>Current Location:</h5>'+
                    '</div>'+
                    '<div class="container col-xs-7">'+
                    '<h5 class="data" id="user_cur_loc"></h5>'+
                    '</div>'+
                    '</div>');
            {% if not general_mobile_view %}
                var room_url = "{% url 'BmsApp:detail_room' 99999 %}".replace(99999, user_data_payload['cur_room_id']);
            {% else %}
                var room_url = "{% url 'BmsApp:detail_room_m' 99999 %}".replace(99999, user_data_payload['cur_room_id']);
            {% endif %}
            var room_link = '<a href="' + room_url + '">' + user_data_payload['cur_room_name'] + '</a>';
            modal_body.find('#user_cur_loc').html(room_link);
        }
        $('.user_rec_modal').on('shown.bs.modal', function () {
            $('.modal-body').css({'max-height': '100%'});
        });

    }
</script>